export const LOGIN_STARTED = "LOGIN_STARTED"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const GET_USER_STARTED = "GET_USER_STARTED"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_ERROR = "GET_USER_ERROR"

export const FETCH_BUYLISTS_STARTED = "FETCH_BUYLISTS_STARTED"
export const FETCH_BUYLISTS_SUCCESS = "FETCH_BUYLISTS_SUCCESS"
export const FETCH_BUYLISTS_ERROR = "FETCH_BUYLISTS_ERROR"

export const ADD_BUYLIST_STARTED = "ADD_BUYLIST_STARTED"
export const ADD_BUYLIST_SUCCESS = "ADD_BUYLIST_SUCCESS"
export const ADD_BUYLIST_ERROR = "ADD_BUYLIST_ERROR"

export const DELETE_BUYLIST_STARTED = "DELETE_BUYLIST_STARTED"
export const DELETE_BUYLIST_SUCCESS = "DELETE_BUYLIST_SUCCESS"
export const DELETE_BUYLIST_ERROR = "DELETE_BUYLIST_ERROR"

export const UPDATE_BUYLIST_STARTED = "UPDATE_BUYLIST_STARTED"
export const UPDATE_BUYLIST_SUCCESS = "UPDATE_BUYLIST_SUCCESS"
export const UPDATE_BUYLIST_ERROR = "UPDATE_BUYLIST_ERROR"

export const FETCH_USERS_STARTED = "FETCH_USERS_STARTED"
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS"
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR"

export const ADD_USER_STARTED = "ADD_USER_STARTED"
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS"
export const ADD_USER_ERROR = "ADD_USER_ERROR"

export const DELETE_USER_STARTED = "DELETE_USER_STARTED"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_ERROR = "DELETE_USER_ERROR"

export const UPDATE_USER_STARTED = "UPDATE_USER_STARTED"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR"
