# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'buylist' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for buylist
  pod 'FirebaseMessaging'

  target 'buylist-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'buylistTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'buylist-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for buylist-tvOS

  target 'buylist-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
